const home=()=>"home page added."
const Nav=()=>"nav is added"
const login=()=>"login page added"
const about=()=>"about page added with conntact info."
const footer=()=>"footer added"
const btn=()=>"login button"